# Generated by Django 4.2.6 on 2023-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lungime', models.FloatField()),
                ('inaltime', models.FloatField()),
                ('pret', models.FloatField()),
            ],
        ),
    ]
