# Generated by Django 4.2.6 on 2023-10-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_sticker_imagine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='inaltime',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='imagine',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='lungime',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='sticker',
            old_name='pret',
            new_name='price',
        ),
    ]
