# Generated by Django 4.2.6 on 2023-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_inaltime_sticker_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
