# Generated by Django 4.2.6 on 2023-10-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_sticker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
