# Generated by Django 4.2.6 on 2023-10-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
