# Generated by Django 4.2.7 on 2023-11-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
