# Generated by Django 4.2.7 on 2023-11-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_sticker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
