# Generated by Django 4.2.7 on 2023-11-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_cart_cartsticker_delete_ordersticker_cart_stickers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
